# Generated by Django 5.1.3 on 2025-02-11 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='credit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='credit',
            old_name='type',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='debt',
            old_name='type',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='category',
            new_name='description',
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('give', 'Give'), ('take', 'Take')], default='give', max_length=4),
        ),
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(default='Other', max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
